O,[CLS],[SEP],B-3,I-3
./outputs/electric-toothbrush_entity_epoch_10_hidden_layer_6_max_seq_len_128_gpu_2
['/export/home/sunhongchao1/1-NLU/Workspace-of-NLU/lexical_analysis/models', '/export/home/sunhongchao1/softwares/anaconda3/lib/python36.zip', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/lib-dynload', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/g2p_seq2seq-6.2.2a0-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/tensor2tensor-1.7.0-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/oauth2client-4.1.3-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/gym-0.12.1-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/gunicorn-19.9.0-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/google_api_python_client-1.7.8-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/future-0.17.1-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/bz2file-0.98-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/rsa-4.0-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/httplib2-0.12.1-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/pyglet-1.4.0b1-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/uritemplate-3.0.0-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/google_auth-1.6.3-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/google_auth_httplib2-0.0.3-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/cachetools-3.1.0-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/bert_base-0.0.9-py3.6.egg', '/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/GPUtil-1.4.0-py3.6.egg', '/export/home/sunhongchao1/1-NLU/Workspace-of-NLU/lexical_analysis/models', '/export/home/sunhongchao1/1-NLU/Workspace-of-NLU/lexical_analysis', '/export/home/sunhongchao1/1-NLU/Workspace-of-NLU']
Traceback (most recent call last):
  File "models/BERT_BIRNN_CRF.py", line 28, in <module>
    from sklearn.metrics import f1_score,precision_score,recall_score
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 27, in <module>
    from scipy.stats import rankdata
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 174, in <module>
    from . import mstats_basic
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site-packages/scipy/stats/mstats_basic.py", line 1082, in <module>
    Ttest_relResult = namedtuple('Ttest_relResult', ('statistic', 'pvalue'))
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/collections/__init__.py", line 429, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt
cp: cannot stat ‘./outputs/electric-toothbrush_entity_epoch_10_hidden_layer_6_max_seq_len_128_gpu_2/entity_test_results.txt’: No such file or directory
sed: can't read ./outputs/electric-toothbrush_entity_epoch_10_hidden_layer_6_max_seq_len_128_gpu_2/entity_test_results.txt: No such file or directory
sed: can't read ./outputs/electric-toothbrush_entity_epoch_10_hidden_layer_6_max_seq_len_128_gpu_2/entity_test_results.txt: No such file or directory
Failed to import the site module
Traceback (most recent call last):
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site.py", line 550, in <module>
    main()
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site.py", line 532, in main
    known_paths = addsitepackages(known_paths)
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site.py", line 320, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/importlib/util.py", line 2, in <module>
    from . import abc
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/importlib/abc.py", line 285, in <module>
    class SourceLoader(_bootstrap_external.SourceLoader, ResourceLoader, ExecutionLoader):
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/abc.py", line 136, in __new__
    for name, value in namespace.items()
  File "/export/home/sunhongchao1/softwares/anaconda3/lib/python3.6/abc.py", line 137, in <setcomp>
    if getattr(value, "__isabstractmethod__", False)}
KeyboardInterrupt
